spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres?schema=anime
    username: root
    password: root
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    validator-url: ""